version: '3.8'

services:
  mongodb:
    image: mongo:latest
    container_name: mongodb-kanban
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db
    environment:
      - MONGO_INITDB_DATABASE=kanban

  backend:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: backend-kanban
    ports:
      - "4001:4000"
    depends_on:
      - mongodb
    environment:
      - MONGODB_URI=mongodb://mongodb:27017/kanban
      - NODE_ENV=development
    volumes:
      - .:/app
      - /app/node_modules
    command: npm run start:dev

volumes:
  mongodb_data: